name: GitHub Actions Demo
on: [push]
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: none
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: ls
